# Useing official Nginx runtime as a parent image
FROM nginx:alpine

# Copy HTML file into the Nginx document root
COPY index.html /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
