# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: avengers-service
spec:
  selector:
    app: avengers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
